#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GitHub Release 자동 생성 스크립트
매일 자동 실행 시 버전 태그 및 릴리즈 노트를 생성합니다.
"""

import os
import sys
import logging
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from git import Repo
from git.exc import GitCommandError

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)


class AutoRelease:
    """자동 릴리즈 생성기"""
    
    def __init__(self, repo_path: str = None):
        self.repo_path = repo_path or Path(__file__).parent.parent
        self.repo = Repo(self.repo_path)
    
    def get_current_version(self) -> str:
        """현재 버전 가져오기"""
        tags = sorted([t.name for t in self.repo.tags], reverse=True)
        if tags:
            return tags[0]
        return "v0.0.0"
    
    def get_last_release_date(self) -> str:
        """마지막 릴리즈 날짜"""
        try:
            commits = list(self.repo.iter_commits(max_count=1))
            if commits:
                return commits[0].committed_datetime.strftime('%Y-%m-%d %H:%M:%S')
        except:
            pass
        return datetime.now().strftime('%Y-%m-%d')
    
    def should_create_release(self) -> bool:
        """릴리즈 생성 조건 확인"""
        # 데이터 변경이 있는 경우
        if self.repo.is_dirty(untracked_files=True):
            return True
        return False
    
    def create_release_notes(self, version: str) -> str:
        """릴리즈 노트 생성"""
        from wedding_expo_scraper.storage import DataStorage
        import pandas as pd
        
        # 데이터 읽기
        storage = DataStorage()
        csv_path = storage.filepath
        
        data_count = 0
        latest_date = "N/A"
        
        if csv_path.exists():
            try:
                df = pd.read_csv(csv_path)
                data_count = len(df)
                if 'start_date' in df.columns:
                    latest_date = df['start_date'].max()
            except:
                pass
        
        notes = f"""# 🎉 Release {version}

**배포일**: {datetime.now().strftime('%Y-%m-%d')}  
**자동 생성**: 매일 스크래핑 시스템

---

## 📊 이번 업데이트

| 항목 | 내용 |
|------|------|
| 데이터 건수 | {data_count}건 |
| 최신 일정 | {latest_date} |
| 생성 시간 | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |

---

## 🔄 자동 업데이트 내역

이 버전은 매일 자동 스크래핑 시스템에 의해 생성되었습니다.

### 업데이트 내용
- 데이터 스크래핑 ({data_count}건)
- 날짜/장소 정규화
- GitHub 자동 동기화
- 알림 발송

---

*Auto-generated by Wedding Expo Scraper*
"""
        return notes
    
    def create_tag(self, version: str, message: str = None) -> bool:
        """태그 생성"""
        try:
            # 기존 태그 확인
            existing = [t.name for t in self.repo.tags]
            if version in existing:
                logger.info(f"⚠️ 태그 {version} 이미 존재")
                return True
            
            # 태그 생성
            if message is None:
                message = f"Release {version}"
            
            self.repo.create_tag(version, message=message)
            logger.info(f"✅ 태그 생성: {version}")
            return True
            
        except GitCommandError as e:
            logger.error(f"❌ 태그 생성 실패: {e}")
            return False
    
    def push_tag(self, version: str) -> bool:
        """태그 푸시"""
        try:
            origin = self.repo.remote('origin')
            origin.push(version)
            logger.info(f"✅ 태그 푸시 완료: {version}")
            return True
        except GitCommandError as e:
            logger.error(f"❌ 태그 푸시 실패: {e}")
            return False
    
    def create_github_release(self, version: str, release_notes: str, tag_name: str = None) -> bool:
        """GitHub Release 생성 (gh CLI 사용)"""
        import subprocess
        
        if tag_name is None:
            tag_name = version
        
        try:
            # 릴리즈 노트를 임시 파일에 저장
            notes_file = Path(self.repo_path) / f".release_notes_{version}.tmp"
            notes_file.write_text(release_notes, encoding='utf-8')
            
            # gh release create 명령 실행
            cmd = [
                "gh", "release", "create", tag_name,
                "--title", f"Wedding Expo Scraper {version}",
                "--notes-file", str(notes_file),
                "--latest"
            ]
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=self.repo_path
            )
            
            # 임시 파일 삭제
            if notes_file.exists():
                notes_file.unlink()
            
            if result.returncode == 0:
                logger.info(f"✅ GitHub Release 생성 완료: {tag_name}")
                return True
            else:
                logger.warning(f"⚠️ GitHub Release 생성 실패: {result.stderr}")
                return False
                
        except FileNotFoundError:
            logger.warning("⚠️ gh CLI가 설치되지 않았습니다. GitHub Releases에서 수동으로 생성하세요.")
            return False
        except Exception as e:
            logger.error(f"❌ GitHub Release 생성 오류: {e}")
            return False
    
    def run(self, create_release: bool = True) -> bool:
        """릴리즈 자동 생성 실행"""
        logger.info("=" * 50)
        logger.info("🚀 자동 릴리즈 생성 시작")
        logger.info("=" * 50)
        
        # 현재 버전
        current_version = self.get_current_version()
        logger.info(f"현재 버전: {current_version}")
        
        # 변경 사항 확인
        if not self.should_create_release():
            logger.info("변경 사항 없어 릴리즈 생성을 건너뜁니다.")
            return True
        
        # 새 버전 생성 (날짜 기반)
        new_version = f"v{datetime.now().strftime('%Y.%m.%d')}"
        logger.info(f"새 버전: {new_version}")
        
        # 릴리즈 노트 생성
        release_notes = self.create_release_notes(new_version)
        
        # 태그 생성
        if self.create_tag(new_version, release_notes):
            # 태그 푸시
            if create_release:
                self.push_tag(new_version)
                # GitHub Release 생성
                self.create_github_release(new_version, release_notes)
                logger.info("🎉 GitHub Release 생성 완료!")
        
        logger.info("=" * 50)
        return True


def main():
    release = AutoRelease()
    release.run()


if __name__ == "__main__":
    main()
